Awards/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include("polls.urls")),
]

polls/urls.py
from django.urls import path

from . import views
app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="details"),
    path("<int:pk>/results/", views.ResultView.as_view(), name="result"),
    path("<int:question_id>/votes/", views.votes, name="votes"),
]

polls/models.py
# Django
import datetime

from django.contrib import admin
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(hours=36)

    def __str__(self):
        return self.question_text

    class Meta:
        ordering = ["pub_date"]


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

    class Meta:
        ordering = ["votes"]

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from polls.models import Question, Choice


# Create your views here.

# def index(request):
#     last_question_list = Question.objects.all()
#     print(last_question_list)
#     return render(request, "polls/index.html", {
#         "last_question_list": last_question_list})
#
#
# def detail(request, question_id):
#     questions: Question = get_object_or_404(Question, pk= question_id)
#     return render(request, "polls/details.html", {
#         "question": questions})
#
#
# def result(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "polls/results.html",{"question":question})

# Clase Base Views

class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "last_question_list"

    def get_queryset(self):
        """Return the last five published questions"""
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/details.html"


class ResultView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


def votes(request, question_id):
    question: Question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(request, "polls/details.html", {
            "question": question,
            "error_message": "No elegiste una respuesta"
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:result", args=(question.id,)))

templates/polls/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ question.question_text }}</title>
</head>
<body>
<form action="{% url 'polls:votes' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        {% for choice in question.choice_set.all %}
            <div>
                <input
                    type="radio"
                    name="choice"
                    id="choice{{ forloop.counter }}"
                    value="{{ choice.id }}"
                >
                <label for="choice{{ forloop.counter }}">
                    {{ choice.choice_text }}
                </label>
            </div>
            <br>
        {% endfor %}
    </fieldset>
    <input type="Submit" name="submit" value="Votar">
    </form>


<!--{% if question.choice_set.all %}
    <h1>{{question.question_text}}</h1>
        <ul>
    {% for choice in question.choice_set.all %}
        <li>{{choice.choice_text}}</li>
    {% endfor %}
        </ul>
{% else %}
   
    <p> no hay</p>
{% endif %}-->
</body>
</html>

templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/polls/style.css' %}">
</head>
<body>
{% if last_question_list %}
    <ul>
        {% for question in last_question_list %}
            <li class="color-change shadow-pop-bl"><a href="{% url 'polls:details' question.id %}"> {{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No hay encuestas pendientes</p>
{% endif %}

</body>
</html>

templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ question.question_text }}</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{choice.votes|pluralize}}</li>
{% endfor %}
<br>
<a href="{% url 'polls:details' question.id %}">¿Te gustaria volver a votar?</a>
<!--
Para las palabras que no se pluralizan con un sufijo simple,
puede especificar un sufijo singular y plural, separados por una coma.
You have {{ num_cherries }} cherr{{ num_cherries|pluralize:"y,ies" }}.
-->
</body>
</html>